# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/money-open-exchange-rates/all/money-open-exchange-rates.rbi
#
# money-open-exchange-rates-1.3.0

module OpenExchangeRatesBank
end
class Money
end
module Money::Bank
end
class Money::Bank::InvalidCache < StandardError
end
class Money::Bank::NoAppId < StandardError
end
class Money::Bank::OpenExchangeRatesBank < Money::Bank::VariableExchange
  def api_response; end
  def app_id; end
  def app_id=(arg0); end
  def cache; end
  def cache=(arg0); end
  def calc_pair_rate_using_base(from_currency, to_currency, opts); end
  def date; end
  def date=(arg0); end
  def exchange_rates; end
  def expire_rates; end
  def force_refresh_rate_on_expire; end
  def force_refresh_rate_on_expire=(arg0); end
  def get_rate(from_currency, to_currency, opts = nil); end
  def get_rate_or_calc_inverse(from_currency, to_currency, opts = nil); end
  def historical_url; end
  def json_response; end
  def latest_url; end
  def oer_rates; end
  def oer_url; end
  def prettyprint; end
  def prettyprint=(arg0); end
  def rates_expiration; end
  def rates_timestamp; end
  def rates_timestamp=(at); end
  def read_from_cache; end
  def read_from_url; end
  def refresh_rates; end
  def refresh_rates_expiration; end
  def save_cache; end
  def save_rates; end
  def show_alternative; end
  def show_alternative=(arg0); end
  def source; end
  def source=(value); end
  def source_url; end
  def store_in_cache(text); end
  def super_get_rate(from, to, opts = nil); end
  def symbols; end
  def symbols=(arg0); end
  def ttl_in_seconds; end
  def ttl_in_seconds=(value); end
  def update_rates; end
  def valid_rates?(text); end
end
