version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - bundle exec rubocop
      - bundle exec srb tc --progress --ignore vendor/bundle
      - bundle exec rspec --order random

