name: RSpec

on: [push, pull_request]

env:
  RUBY_VERSION: 3.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        id: ruby
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - uses: actions/cache@v1
        id: cache
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}

      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: DB migration
        run: bundle exec rails db:create db:schema:load

      - name: Linter
        run: bundle exec rubocop

      - name: Type check
        run: bundle exec srb tc --progress --ignore vendor/bundle

      - name: Unit tests
        run: bundle exec rspec --order random
